# # Note: make sure you uncomment this file before deploying

# version: 2.1
# orbs:
#   #terraform: circleci/terraform@3.0.0
#   aws-ecr: circleci/aws-ecr@7.3.0
#   slack: circleci/slack@4.6.0

# #circleci run and push image to ecr then 
# #deploy infra run to build the infra and ecs
# #connect ecs to ecr to create the task or run infra first but how does ecs wait for image to be put in ecr
# #slack orb is used to integrate circleci with slack, so we can be notified of deployment fails/passes

# jobs:
#   python_test:
#     docker:
#       - image: circleci/python:3.7.4
#     steps:
#       - checkout
#       - run:
#           name: Install Python dependencies
#           command: |
#             cd backend/
#             echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
#             pip install --user -r requirements.txt
#       - run:
#           name: Run unit tests
#           command: |
#             pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
#       - slack/notify:
#           channel: $SLACK_DEFAULT_CHANNEL
#           event: fail
#           template: basic_fail_1
#       - slack/notify:
#           channel: $SLACK_DEFAULT_CHANNEL
#           event: pass
#           template: basic_success_1
                           
#       - store_test_results:
#           path: test-reports
#       - store_artifacts:
#           path: test-reports
          
# #  deploy_infra:
# #    working_directory: /tmp/project
# #    docker:
# #      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
# #    steps:
# #      - checkout
# #      - terraform/validate:
# #          path: ./terraform
# #      - terraform/plan:
# #          path: ./terraform
# #      - terraform/apply:
# #          path: ./terraform
     
# workflows:

#   build_test_deploy:
#     jobs:
#       - python_test:
#           context: ei-circleci-alerts 

#  #     - aws-ecr/build-and-push-image:
#  #         region: AWS_DEFAULT_REGION
#  #         account-url: AWS_ECR_ACCOUNT_URL
#  #         create-repo: true
#  #         repo: circle-ci
#  #         tag: latest
#  #         requires:
#  #           - python_test
          
#  #    - deploy_infra:
#  #         context: terraform
#  #         requires:
#  #           - aws-ecr/build-and-push-image
                       